/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: detector.i

package detector

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef long long swig_type_5;
typedef long long swig_type_6;
typedef long long swig_type_7;
typedef long long swig_type_8;
typedef long long swig_type_9;
typedef long long swig_type_10;
typedef long long swig_type_11;
typedef long long swig_type_12;
typedef long long swig_type_13;
typedef long long swig_type_14;
typedef long long swig_type_15;
typedef long long swig_type_16;
typedef long long swig_type_17;
typedef long long swig_type_18;
typedef long long swig_type_19;
typedef long long swig_type_20;
typedef long long swig_type_21;
typedef long long swig_type_22;
typedef long long swig_type_23;
typedef long long swig_type_24;
typedef long long swig_type_25;
typedef long long swig_type_26;
typedef long long swig_type_27;
typedef long long swig_type_28;
typedef long long swig_type_29;
typedef long long swig_type_30;
typedef long long swig_type_31;
typedef long long swig_type_32;
typedef long long swig_type_33;
typedef long long swig_type_34;
typedef long long swig_type_35;
typedef long long swig_type_36;
typedef long long swig_type_37;
typedef long long swig_type_38;
typedef long long swig_type_39;
typedef long long swig_type_40;
typedef long long swig_type_41;
typedef long long swig_type_42;
typedef long long swig_type_43;
typedef long long swig_type_44;
typedef long long swig_type_45;
typedef long long swig_type_46;
typedef long long swig_type_47;
typedef long long swig_type_48;
extern void _wrap_Swig_free_detector_0cbdac121a63e725(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_detector_0cbdac121a63e725(swig_intgo arg1);
extern uintptr_t _wrap_new_rectangle__SWIG_0_detector_0cbdac121a63e725(swig_type_1 arg1, swig_type_2 arg2, swig_type_3 arg3, swig_type_4 arg4);
extern uintptr_t _wrap_new_rectangle__SWIG_1_detector_0cbdac121a63e725(swig_type_5 arg1, swig_type_6 arg2);
extern uintptr_t _wrap_new_rectangle__SWIG_2_detector_0cbdac121a63e725(uintptr_t arg1);
extern uintptr_t _wrap_new_rectangle__SWIG_3_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_new_rectangle__SWIG_5_detector_0cbdac121a63e725(void);
extern swig_type_7 _wrap_rectangle_top__SWIG_0_detector_0cbdac121a63e725(uintptr_t arg1);
extern swig_voidp _wrap_rectangle_top__SWIG_1_detector_0cbdac121a63e725(uintptr_t arg1);
extern void _wrap_rectangle_set_top_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_8 arg2);
extern swig_type_9 _wrap_rectangle_left__SWIG_0_detector_0cbdac121a63e725(uintptr_t arg1);
extern swig_voidp _wrap_rectangle_left__SWIG_1_detector_0cbdac121a63e725(uintptr_t arg1);
extern void _wrap_rectangle_set_left_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_10 arg2);
extern swig_type_11 _wrap_rectangle_right__SWIG_0_detector_0cbdac121a63e725(uintptr_t arg1);
extern swig_voidp _wrap_rectangle_right__SWIG_1_detector_0cbdac121a63e725(uintptr_t arg1);
extern void _wrap_rectangle_set_right_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_12 arg2);
extern swig_type_13 _wrap_rectangle_bottom__SWIG_0_detector_0cbdac121a63e725(uintptr_t arg1);
extern swig_voidp _wrap_rectangle_bottom__SWIG_1_detector_0cbdac121a63e725(uintptr_t arg1);
extern void _wrap_rectangle_set_bottom_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_14 arg2);
extern uintptr_t _wrap_rectangle_tl_corner_detector_0cbdac121a63e725(uintptr_t arg1);
extern uintptr_t _wrap_rectangle_bl_corner_detector_0cbdac121a63e725(uintptr_t arg1);
extern uintptr_t _wrap_rectangle_tr_corner_detector_0cbdac121a63e725(uintptr_t arg1);
extern uintptr_t _wrap_rectangle_br_corner_detector_0cbdac121a63e725(uintptr_t arg1);
extern swig_type_15 _wrap_rectangle_width_detector_0cbdac121a63e725(uintptr_t arg1);
extern swig_type_16 _wrap_rectangle_height_detector_0cbdac121a63e725(uintptr_t arg1);
extern swig_type_17 _wrap_rectangle_area_detector_0cbdac121a63e725(uintptr_t arg1);
extern _Bool _wrap_rectangle_is_empty_detector_0cbdac121a63e725(uintptr_t arg1);
extern uintptr_t _wrap_rectangle_intersect_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2);
extern _Bool _wrap_rectangle_contains__SWIG_0_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2);
extern _Bool _wrap_rectangle_contains__SWIG_1_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_18 arg2, swig_type_19 arg3);
extern _Bool _wrap_rectangle_contains__SWIG_2_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_delete_rectangle_detector_0cbdac121a63e725(uintptr_t arg1);
extern void _wrap_serialize__SWIG_2_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_deserialize__SWIG_2_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_centered_rect__SWIG_0_detector_0cbdac121a63e725(swig_type_20 arg1, swig_type_21 arg2, swig_type_22 arg3, swig_type_23 arg4);
extern uintptr_t _wrap_intersect_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2);
extern swig_type_24 _wrap_area_detector_0cbdac121a63e725(uintptr_t arg1);
extern uintptr_t _wrap_center_detector_0cbdac121a63e725(uintptr_t arg1);
extern uintptr_t _wrap_dcenter_detector_0cbdac121a63e725(uintptr_t arg1);
extern swig_type_25 _wrap_distance_to_rect_edge_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_nearest_point_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2);
extern swig_type_26 _wrap_nearest_rect_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_clip_line_to_rectangle_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_centered_rect__SWIG_1_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_27 arg2, swig_type_28 arg3);
extern uintptr_t _wrap_centered_rect__SWIG_2_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_29 arg2, swig_type_30 arg3);
extern uintptr_t _wrap_shrink_rect__SWIG_0_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_31 arg2);
extern uintptr_t _wrap_grow_rect__SWIG_0_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_32 arg2);
extern uintptr_t _wrap_shrink_rect__SWIG_1_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_33 arg2, swig_type_34 arg3);
extern uintptr_t _wrap_grow_rect__SWIG_1_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_35 arg2, swig_type_36 arg3);
extern uintptr_t _wrap_translate_rect__SWIG_0_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_translate_rect__SWIG_1_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_37 arg2, swig_type_38 arg3);
extern uintptr_t _wrap_resize_rect_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_39 arg2, swig_type_40 arg3);
extern uintptr_t _wrap_resize_rect_width_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_41 arg2);
extern uintptr_t _wrap_resize_rect_height_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_42 arg2);
extern uintptr_t _wrap_move_rect__SWIG_0_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_move_rect__SWIG_1_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_43 arg2, swig_type_44 arg3);
extern uintptr_t _wrap_set_rect_area_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_45 arg2);
extern uintptr_t _wrap_set_aspect_ratio_detector_0cbdac121a63e725(uintptr_t arg1, double arg2);
extern uintptr_t _wrap_new_full_object_detection__SWIG_0_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_new_full_object_detection__SWIG_1_detector_0cbdac121a63e725(void);
extern uintptr_t _wrap_new_full_object_detection__SWIG_2_detector_0cbdac121a63e725(uintptr_t arg1);
extern uintptr_t _wrap_full_object_detection_get_rect__SWIG_0_detector_0cbdac121a63e725(uintptr_t arg1);
extern uintptr_t _wrap_full_object_detection_get_rect__SWIG_1_detector_0cbdac121a63e725(uintptr_t arg1);
extern swig_type_46 _wrap_full_object_detection_num_parts_detector_0cbdac121a63e725(uintptr_t arg1);
extern uintptr_t _wrap_full_object_detection_part__SWIG_0_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_47 arg2);
extern uintptr_t _wrap_full_object_detection_part__SWIG_1_detector_0cbdac121a63e725(uintptr_t arg1, swig_type_48 arg2);
extern void _wrap_delete_full_object_detection_detector_0cbdac121a63e725(uintptr_t arg1);
extern _Bool _wrap_all_parts_in_rect_detector_0cbdac121a63e725(uintptr_t arg1);
extern uintptr_t _wrap_new_mmod_rect__SWIG_0_detector_0cbdac121a63e725(void);
extern uintptr_t _wrap_new_mmod_rect__SWIG_1_detector_0cbdac121a63e725(uintptr_t arg1);
extern uintptr_t _wrap_new_mmod_rect__SWIG_2_detector_0cbdac121a63e725(uintptr_t arg1, double arg2);
extern uintptr_t _wrap_new_mmod_rect__SWIG_3_detector_0cbdac121a63e725(uintptr_t arg1, double arg2, uintptr_t arg3);
extern void _wrap_mmod_rect_rect_set_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_mmod_rect_rect_get_detector_0cbdac121a63e725(uintptr_t arg1);
extern void _wrap_mmod_rect_detection_confidence_set_detector_0cbdac121a63e725(uintptr_t arg1, double arg2);
extern double _wrap_mmod_rect_detection_confidence_get_detector_0cbdac121a63e725(uintptr_t arg1);
extern void _wrap_mmod_rect_ignore_set_detector_0cbdac121a63e725(uintptr_t arg1, _Bool arg2);
extern _Bool _wrap_mmod_rect_ignore_get_detector_0cbdac121a63e725(uintptr_t arg1);
extern void _wrap_mmod_rect_label_set_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_mmod_rect_label_get_detector_0cbdac121a63e725(uintptr_t arg1);
extern void _wrap_delete_mmod_rect_detector_0cbdac121a63e725(uintptr_t arg1);
extern uintptr_t _wrap_ignored_mmod_rect_detector_0cbdac121a63e725(uintptr_t arg1);
extern void _wrap_serialize__SWIG_3_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_deserialize__SWIG_3_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_ProcessRect_detector_0cbdac121a63e725(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_detector_0cbdac121a63e725(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrRectangle uintptr

func (p SwigcptrRectangle) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrRectangle) SwigIsRectangle() {
}

func NewRectangle__SWIG_0(arg1 int64, arg2 int64, arg3 int64, arg4 int64) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_new_rectangle__SWIG_0_detector_0cbdac121a63e725(C.swig_type_1(_swig_i_0), C.swig_type_2(_swig_i_1), C.swig_type_3(_swig_i_2), C.swig_type_4(_swig_i_3))))
	return swig_r
}

func NewRectangle__SWIG_1(arg1 uint64, arg2 uint64) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_new_rectangle__SWIG_1_detector_0cbdac121a63e725(C.swig_type_5(_swig_i_0), C.swig_type_6(_swig_i_1))))
	return swig_r
}

func NewRectangle__SWIG_2(arg1 Dlib_vector_Sl_long_Sc_2_Sg_) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_new_rectangle__SWIG_2_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewRectangle__SWIG_3(arg1 Dlib_vector_Sl_long_Sc_2_Sg_, arg2 Dlib_vector_Sl_long_Sc_2_Sg_) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_new_rectangle__SWIG_3_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func NewRectangle__SWIG_5() (_swig_ret Rectangle) {
	var swig_r Rectangle
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_new_rectangle__SWIG_5_detector_0cbdac121a63e725()))
	return swig_r
}

func NewRectangle(a ...interface{}) Rectangle {
	argc := len(a)
	if argc == 0 {
		return NewRectangle__SWIG_5()
	}
	if argc == 1 {
		return NewRectangle__SWIG_2(a[0].(Dlib_vector_Sl_long_Sc_2_Sg_))
	}
	if argc == 2 {
		if _, ok := a[0].(SwigcptrDlib_vector_Sl_long_Sc_2_Sg_); !ok {
			goto check_3
		}
		if _, ok := a[1].(SwigcptrDlib_vector_Sl_long_Sc_2_Sg_); !ok {
			goto check_3
		}
		return NewRectangle__SWIG_3(a[0].(Dlib_vector_Sl_long_Sc_2_Sg_), a[1].(Dlib_vector_Sl_long_Sc_2_Sg_))
	}
check_3:
	if argc == 2 {
		return NewRectangle__SWIG_1(a[0].(uint64), a[1].(uint64))
	}
	if argc == 4 {
		return NewRectangle__SWIG_0(a[0].(int64), a[1].(int64), a[2].(int64), a[3].(int64))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrRectangle) Top__SWIG_0() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_rectangle_top__SWIG_0_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrRectangle) Top__SWIG_1() (_swig_ret *int64) {
	var swig_r *int64
	_swig_i_0 := arg1
	swig_r = (*int64)(C._wrap_rectangle_top__SWIG_1_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrRectangle) Top(a ...interface{}) interface{} {
	argc := len(a)
	if argc == 0 {
		return p.Top__SWIG_0()
	}
	if argc == 0 {
		return p.Top__SWIG_1()
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrRectangle) Set_top(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_rectangle_set_top_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_8(_swig_i_1))
}

func (arg1 SwigcptrRectangle) Left__SWIG_0() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_rectangle_left__SWIG_0_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrRectangle) Left__SWIG_1() (_swig_ret *int64) {
	var swig_r *int64
	_swig_i_0 := arg1
	swig_r = (*int64)(C._wrap_rectangle_left__SWIG_1_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrRectangle) Left(a ...interface{}) interface{} {
	argc := len(a)
	if argc == 0 {
		return p.Left__SWIG_0()
	}
	if argc == 0 {
		return p.Left__SWIG_1()
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrRectangle) Set_left(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_rectangle_set_left_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_10(_swig_i_1))
}

func (arg1 SwigcptrRectangle) Right__SWIG_0() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_rectangle_right__SWIG_0_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrRectangle) Right__SWIG_1() (_swig_ret *int64) {
	var swig_r *int64
	_swig_i_0 := arg1
	swig_r = (*int64)(C._wrap_rectangle_right__SWIG_1_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrRectangle) Right(a ...interface{}) interface{} {
	argc := len(a)
	if argc == 0 {
		return p.Right__SWIG_0()
	}
	if argc == 0 {
		return p.Right__SWIG_1()
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrRectangle) Set_right(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_rectangle_set_right_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_12(_swig_i_1))
}

func (arg1 SwigcptrRectangle) Bottom__SWIG_0() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_rectangle_bottom__SWIG_0_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrRectangle) Bottom__SWIG_1() (_swig_ret *int64) {
	var swig_r *int64
	_swig_i_0 := arg1
	swig_r = (*int64)(C._wrap_rectangle_bottom__SWIG_1_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (p SwigcptrRectangle) Bottom(a ...interface{}) interface{} {
	argc := len(a)
	if argc == 0 {
		return p.Bottom__SWIG_0()
	}
	if argc == 0 {
		return p.Bottom__SWIG_1()
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrRectangle) Set_bottom(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_rectangle_set_bottom_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_14(_swig_i_1))
}

func (arg1 SwigcptrRectangle) Tl_corner() (_swig_ret Dlib_vector_Sl_long_Sc_2_Sg_) {
	var swig_r Dlib_vector_Sl_long_Sc_2_Sg_
	_swig_i_0 := arg1
	swig_r = (Dlib_vector_Sl_long_Sc_2_Sg_)(SwigcptrDlib_vector_Sl_long_Sc_2_Sg_(C._wrap_rectangle_tl_corner_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrRectangle) Bl_corner() (_swig_ret Dlib_vector_Sl_long_Sc_2_Sg_) {
	var swig_r Dlib_vector_Sl_long_Sc_2_Sg_
	_swig_i_0 := arg1
	swig_r = (Dlib_vector_Sl_long_Sc_2_Sg_)(SwigcptrDlib_vector_Sl_long_Sc_2_Sg_(C._wrap_rectangle_bl_corner_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrRectangle) Tr_corner() (_swig_ret Dlib_vector_Sl_long_Sc_2_Sg_) {
	var swig_r Dlib_vector_Sl_long_Sc_2_Sg_
	_swig_i_0 := arg1
	swig_r = (Dlib_vector_Sl_long_Sc_2_Sg_)(SwigcptrDlib_vector_Sl_long_Sc_2_Sg_(C._wrap_rectangle_tr_corner_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrRectangle) Br_corner() (_swig_ret Dlib_vector_Sl_long_Sc_2_Sg_) {
	var swig_r Dlib_vector_Sl_long_Sc_2_Sg_
	_swig_i_0 := arg1
	swig_r = (Dlib_vector_Sl_long_Sc_2_Sg_)(SwigcptrDlib_vector_Sl_long_Sc_2_Sg_(C._wrap_rectangle_br_corner_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrRectangle) Width() (_swig_ret uint64) {
	var swig_r uint64
	_swig_i_0 := arg1
	swig_r = (uint64)(C._wrap_rectangle_width_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrRectangle) Height() (_swig_ret uint64) {
	var swig_r uint64
	_swig_i_0 := arg1
	swig_r = (uint64)(C._wrap_rectangle_height_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrRectangle) Area() (_swig_ret uint64) {
	var swig_r uint64
	_swig_i_0 := arg1
	swig_r = (uint64)(C._wrap_rectangle_area_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrRectangle) Is_empty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_rectangle_is_empty_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrRectangle) Intersect(arg2 Rectangle) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_rectangle_intersect_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrRectangle) Contains__SWIG_0(arg2 Dlib_vector_Sl_long_Sc_2_Sg_) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (bool)(C._wrap_rectangle_contains__SWIG_0_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func (arg1 SwigcptrRectangle) Contains__SWIG_1(arg2 int64, arg3 int64) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (bool)(C._wrap_rectangle_contains__SWIG_1_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_18(_swig_i_1), C.swig_type_19(_swig_i_2)))
	return swig_r
}

func (arg1 SwigcptrRectangle) Contains__SWIG_2(arg2 Rectangle) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (bool)(C._wrap_rectangle_contains__SWIG_2_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func (p SwigcptrRectangle) Contains(a ...interface{}) bool {
	argc := len(a)
	if argc == 1 {
		if _, ok := a[0].(SwigcptrDlib_vector_Sl_long_Sc_2_Sg_); !ok {
			goto check_1
		}
		return p.Contains__SWIG_0(a[0].(Dlib_vector_Sl_long_Sc_2_Sg_))
	}
check_1:
	if argc == 1 {
		return p.Contains__SWIG_2(a[0].(Rectangle))
	}
	if argc == 2 {
		return p.Contains__SWIG_1(a[0].(int64), a[1].(int64))
	}
	panic("No match for overloaded function call")
}

func DeleteRectangle(arg1 Rectangle) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_rectangle_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))
}

type Rectangle interface {
	Swigcptr() uintptr
	SwigIsRectangle()
	Top(a ...interface{}) interface{}
	Set_top(arg2 int64)
	Left(a ...interface{}) interface{}
	Set_left(arg2 int64)
	Right(a ...interface{}) interface{}
	Set_right(arg2 int64)
	Bottom(a ...interface{}) interface{}
	Set_bottom(arg2 int64)
	Tl_corner() (_swig_ret Dlib_vector_Sl_long_Sc_2_Sg_)
	Bl_corner() (_swig_ret Dlib_vector_Sl_long_Sc_2_Sg_)
	Tr_corner() (_swig_ret Dlib_vector_Sl_long_Sc_2_Sg_)
	Br_corner() (_swig_ret Dlib_vector_Sl_long_Sc_2_Sg_)
	Width() (_swig_ret uint64)
	Height() (_swig_ret uint64)
	Area() (_swig_ret uint64)
	Is_empty() (_swig_ret bool)
	Intersect(arg2 Rectangle) (_swig_ret Rectangle)
	Contains(a ...interface{}) bool
}

func Serialize__SWIG_2(arg1 Rectangle, arg2 Std_ostream) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_serialize__SWIG_2_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Deserialize__SWIG_2(arg1 Rectangle, arg2 Std_istream) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_deserialize__SWIG_2_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Centered_rect__SWIG_0(arg1 int64, arg2 int64, arg3 uint64, arg4 uint64) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_centered_rect__SWIG_0_detector_0cbdac121a63e725(C.swig_type_20(_swig_i_0), C.swig_type_21(_swig_i_1), C.swig_type_22(_swig_i_2), C.swig_type_23(_swig_i_3))))
	return swig_r
}

func Intersect(arg1 Rectangle, arg2 Rectangle) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_intersect_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Area(arg1 Rectangle) (_swig_ret uint64) {
	var swig_r uint64
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint64)(C._wrap_area_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Center(arg1 Rectangle) (_swig_ret Dlib_vector_Sl_long_Sc_2_Sg_) {
	var swig_r Dlib_vector_Sl_long_Sc_2_Sg_
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Dlib_vector_Sl_long_Sc_2_Sg_)(SwigcptrDlib_vector_Sl_long_Sc_2_Sg_(C._wrap_center_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Dcenter(arg1 Rectangle) (_swig_ret Dlib_vector_Sl_double_Sc_2_Sg_) {
	var swig_r Dlib_vector_Sl_double_Sc_2_Sg_
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Dlib_vector_Sl_double_Sc_2_Sg_)(SwigcptrDlib_vector_Sl_double_Sc_2_Sg_(C._wrap_dcenter_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Distance_to_rect_edge(arg1 Rectangle, arg2 Dlib_vector_Sl_long_Sc_2_Sg_) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int64)(C._wrap_distance_to_rect_edge_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Nearest_point(arg1 Rectangle, arg2 Dlib_vector_Sl_long_Sc_2_Sg_) (_swig_ret Dlib_vector_Sl_long_Sc_2_Sg_) {
	var swig_r Dlib_vector_Sl_long_Sc_2_Sg_
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Dlib_vector_Sl_long_Sc_2_Sg_)(SwigcptrDlib_vector_Sl_long_Sc_2_Sg_(C._wrap_nearest_point_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Nearest_rect(arg1 Std_vector_Sl_dlib_rectangle_Sg_, arg2 Dlib_vector_Sl_long_Sc_2_Sg_) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int64)(C._wrap_nearest_rect_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Clip_line_to_rectangle(arg1 Rectangle, arg2 Dlib_vector_Sl_long_Sc_2_Sg_, arg3 Dlib_vector_Sl_long_Sc_2_Sg_) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_clip_line_to_rectangle_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func Centered_rect__SWIG_1(arg1 Dlib_vector_Sl_long_Sc_2_Sg_, arg2 uint64, arg3 uint64) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_centered_rect__SWIG_1_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_27(_swig_i_1), C.swig_type_28(_swig_i_2))))
	return swig_r
}

func Centered_rect__SWIG_2(arg1 Rectangle, arg2 uint64, arg3 uint64) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_centered_rect__SWIG_2_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_29(_swig_i_1), C.swig_type_30(_swig_i_2))))
	return swig_r
}

func Centered_rect(a ...interface{}) Rectangle {
	argc := len(a)
	if argc == 3 {
		if _, ok := a[0].(SwigcptrDlib_vector_Sl_long_Sc_2_Sg_); !ok {
			goto check_1
		}
		return Centered_rect__SWIG_1(a[0].(Dlib_vector_Sl_long_Sc_2_Sg_), a[1].(uint64), a[2].(uint64))
	}
check_1:
	if argc == 3 {
		return Centered_rect__SWIG_2(a[0].(Rectangle), a[1].(uint64), a[2].(uint64))
	}
	if argc == 4 {
		return Centered_rect__SWIG_0(a[0].(int64), a[1].(int64), a[2].(uint64), a[3].(uint64))
	}
	panic("No match for overloaded function call")
}

func Shrink_rect__SWIG_0(arg1 Rectangle, arg2 int64) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_shrink_rect__SWIG_0_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_31(_swig_i_1))))
	return swig_r
}

func Grow_rect__SWIG_0(arg1 Rectangle, arg2 int64) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_grow_rect__SWIG_0_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_32(_swig_i_1))))
	return swig_r
}

func Shrink_rect__SWIG_1(arg1 Rectangle, arg2 int64, arg3 int64) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_shrink_rect__SWIG_1_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_33(_swig_i_1), C.swig_type_34(_swig_i_2))))
	return swig_r
}

func Shrink_rect(a ...interface{}) Rectangle {
	argc := len(a)
	if argc == 2 {
		return Shrink_rect__SWIG_0(a[0].(Rectangle), a[1].(int64))
	}
	if argc == 3 {
		return Shrink_rect__SWIG_1(a[0].(Rectangle), a[1].(int64), a[2].(int64))
	}
	panic("No match for overloaded function call")
}

func Grow_rect__SWIG_1(arg1 Rectangle, arg2 int64, arg3 int64) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_grow_rect__SWIG_1_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_35(_swig_i_1), C.swig_type_36(_swig_i_2))))
	return swig_r
}

func Grow_rect(a ...interface{}) Rectangle {
	argc := len(a)
	if argc == 2 {
		return Grow_rect__SWIG_0(a[0].(Rectangle), a[1].(int64))
	}
	if argc == 3 {
		return Grow_rect__SWIG_1(a[0].(Rectangle), a[1].(int64), a[2].(int64))
	}
	panic("No match for overloaded function call")
}

func Translate_rect__SWIG_0(arg1 Rectangle, arg2 Dlib_vector_Sl_long_Sc_2_Sg_) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_translate_rect__SWIG_0_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Translate_rect__SWIG_1(arg1 Rectangle, arg2 int64, arg3 int64) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_translate_rect__SWIG_1_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_37(_swig_i_1), C.swig_type_38(_swig_i_2))))
	return swig_r
}

func Translate_rect(a ...interface{}) Rectangle {
	argc := len(a)
	if argc == 2 {
		return Translate_rect__SWIG_0(a[0].(Rectangle), a[1].(Dlib_vector_Sl_long_Sc_2_Sg_))
	}
	if argc == 3 {
		return Translate_rect__SWIG_1(a[0].(Rectangle), a[1].(int64), a[2].(int64))
	}
	panic("No match for overloaded function call")
}

func Resize_rect(arg1 Rectangle, arg2 uint64, arg3 uint64) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_resize_rect_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_39(_swig_i_1), C.swig_type_40(_swig_i_2))))
	return swig_r
}

func Resize_rect_width(arg1 Rectangle, arg2 uint64) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_resize_rect_width_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_41(_swig_i_1))))
	return swig_r
}

func Resize_rect_height(arg1 Rectangle, arg2 uint64) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_resize_rect_height_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_42(_swig_i_1))))
	return swig_r
}

func Move_rect__SWIG_0(arg1 Rectangle, arg2 Dlib_vector_Sl_long_Sc_2_Sg_) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_move_rect__SWIG_0_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Move_rect__SWIG_1(arg1 Rectangle, arg2 int64, arg3 int64) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_move_rect__SWIG_1_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_43(_swig_i_1), C.swig_type_44(_swig_i_2))))
	return swig_r
}

func Move_rect(a ...interface{}) Rectangle {
	argc := len(a)
	if argc == 2 {
		return Move_rect__SWIG_0(a[0].(Rectangle), a[1].(Dlib_vector_Sl_long_Sc_2_Sg_))
	}
	if argc == 3 {
		return Move_rect__SWIG_1(a[0].(Rectangle), a[1].(int64), a[2].(int64))
	}
	panic("No match for overloaded function call")
}

func Set_rect_area(arg1 Rectangle, arg2 uint64) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_set_rect_area_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_45(_swig_i_1))))
	return swig_r
}

func Set_aspect_ratio(arg1 Rectangle, arg2 float64) (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_set_aspect_ratio_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))))
	return swig_r
}

type SwigcptrFull_object_detection uintptr

func (p SwigcptrFull_object_detection) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrFull_object_detection) SwigIsFull_object_detection() {
}

func NewFull_object_detection__SWIG_0(arg1 Rectangle, arg2 Std_vector_Sl_dlib_vector_Sl_long_Sc_2_Sg__Sg_) (_swig_ret Full_object_detection) {
	var swig_r Full_object_detection
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Full_object_detection)(SwigcptrFull_object_detection(C._wrap_new_full_object_detection__SWIG_0_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func NewFull_object_detection__SWIG_1() (_swig_ret Full_object_detection) {
	var swig_r Full_object_detection
	swig_r = (Full_object_detection)(SwigcptrFull_object_detection(C._wrap_new_full_object_detection__SWIG_1_detector_0cbdac121a63e725()))
	return swig_r
}

func NewFull_object_detection__SWIG_2(arg1 Rectangle) (_swig_ret Full_object_detection) {
	var swig_r Full_object_detection
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Full_object_detection)(SwigcptrFull_object_detection(C._wrap_new_full_object_detection__SWIG_2_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewFull_object_detection(a ...interface{}) Full_object_detection {
	argc := len(a)
	if argc == 0 {
		return NewFull_object_detection__SWIG_1()
	}
	if argc == 1 {
		return NewFull_object_detection__SWIG_2(a[0].(Rectangle))
	}
	if argc == 2 {
		return NewFull_object_detection__SWIG_0(a[0].(Rectangle), a[1].(Std_vector_Sl_dlib_vector_Sl_long_Sc_2_Sg__Sg_))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrFull_object_detection) Get_rect__SWIG_0() (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_full_object_detection_get_rect__SWIG_0_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrFull_object_detection) Get_rect__SWIG_1() (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_full_object_detection_get_rect__SWIG_1_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (p SwigcptrFull_object_detection) Get_rect(a ...interface{}) interface{} {
	argc := len(a)
	if argc == 0 {
		return p.Get_rect__SWIG_0()
	}
	if argc == 0 {
		return p.Get_rect__SWIG_1()
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrFull_object_detection) Num_parts() (_swig_ret uint64) {
	var swig_r uint64
	_swig_i_0 := arg1
	swig_r = (uint64)(C._wrap_full_object_detection_num_parts_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrFull_object_detection) Part__SWIG_0(arg2 uint64) (_swig_ret Dlib_vector_Sl_long_Sc_2_Sg_) {
	var swig_r Dlib_vector_Sl_long_Sc_2_Sg_
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Dlib_vector_Sl_long_Sc_2_Sg_)(SwigcptrDlib_vector_Sl_long_Sc_2_Sg_(C._wrap_full_object_detection_part__SWIG_0_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_47(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrFull_object_detection) Part__SWIG_1(arg2 uint64) (_swig_ret Dlib_vector_Sl_long_Sc_2_Sg_) {
	var swig_r Dlib_vector_Sl_long_Sc_2_Sg_
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (Dlib_vector_Sl_long_Sc_2_Sg_)(SwigcptrDlib_vector_Sl_long_Sc_2_Sg_(C._wrap_full_object_detection_part__SWIG_1_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.swig_type_48(_swig_i_1))))
	return swig_r
}

func (p SwigcptrFull_object_detection) Part(a ...interface{}) interface{} {
	argc := len(a)
	if argc == 1 {
		return p.Part__SWIG_0(a[0].(uint64))
	}
	if argc == 1 {
		return p.Part__SWIG_1(a[0].(uint64))
	}
	panic("No match for overloaded function call")
}

func DeleteFull_object_detection(arg1 Full_object_detection) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_full_object_detection_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))
}

type Full_object_detection interface {
	Swigcptr() uintptr
	SwigIsFull_object_detection()
	Get_rect(a ...interface{}) interface{}
	Num_parts() (_swig_ret uint64)
	Part(a ...interface{}) interface{}
}

func All_parts_in_rect(arg1 Full_object_detection) (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (bool)(C._wrap_all_parts_in_rect_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0)))
	return swig_r
}

type SwigcptrMmod_rect uintptr

func (p SwigcptrMmod_rect) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrMmod_rect) SwigIsMmod_rect() {
}

func NewMmod_rect__SWIG_0() (_swig_ret Mmod_rect) {
	var swig_r Mmod_rect
	swig_r = (Mmod_rect)(SwigcptrMmod_rect(C._wrap_new_mmod_rect__SWIG_0_detector_0cbdac121a63e725()))
	return swig_r
}

func NewMmod_rect__SWIG_1(arg1 Rectangle) (_swig_ret Mmod_rect) {
	var swig_r Mmod_rect
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Mmod_rect)(SwigcptrMmod_rect(C._wrap_new_mmod_rect__SWIG_1_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewMmod_rect__SWIG_2(arg1 Rectangle, arg2 float64) (_swig_ret Mmod_rect) {
	var swig_r Mmod_rect
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Mmod_rect)(SwigcptrMmod_rect(C._wrap_new_mmod_rect__SWIG_2_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))))
	return swig_r
}

func NewMmod_rect__SWIG_3(arg1 Rectangle, arg2 float64, arg3 Std_string) (_swig_ret Mmod_rect) {
	var swig_r Mmod_rect
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (Mmod_rect)(SwigcptrMmod_rect(C._wrap_new_mmod_rect__SWIG_3_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.double(_swig_i_1), C.uintptr_t(_swig_i_2))))
	return swig_r
}

func NewMmod_rect(a ...interface{}) Mmod_rect {
	argc := len(a)
	if argc == 0 {
		return NewMmod_rect__SWIG_0()
	}
	if argc == 1 {
		return NewMmod_rect__SWIG_1(a[0].(Rectangle))
	}
	if argc == 2 {
		return NewMmod_rect__SWIG_2(a[0].(Rectangle), a[1].(float64))
	}
	if argc == 3 {
		return NewMmod_rect__SWIG_3(a[0].(Rectangle), a[1].(float64), a[2].(Std_string))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrMmod_rect) SetRect(arg2 Rectangle) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_mmod_rect_rect_set_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrMmod_rect) GetRect() (_swig_ret Rectangle) {
	var swig_r Rectangle
	_swig_i_0 := arg1
	swig_r = (Rectangle)(SwigcptrRectangle(C._wrap_mmod_rect_rect_get_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func (arg1 SwigcptrMmod_rect) SetDetection_confidence(arg2 float64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_mmod_rect_detection_confidence_set_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))
}

func (arg1 SwigcptrMmod_rect) GetDetection_confidence() (_swig_ret float64) {
	var swig_r float64
	_swig_i_0 := arg1
	swig_r = (float64)(C._wrap_mmod_rect_detection_confidence_get_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrMmod_rect) SetIgnore(arg2 bool) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_mmod_rect_ignore_set_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C._Bool(_swig_i_1))
}

func (arg1 SwigcptrMmod_rect) GetIgnore() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_mmod_rect_ignore_get_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrMmod_rect) SetLabel(arg2 Std_string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_mmod_rect_label_set_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrMmod_rect) GetLabel() (_swig_ret Std_string) {
	var swig_r Std_string
	_swig_i_0 := arg1
	swig_r = (Std_string)(SwigcptrStd_string(C._wrap_mmod_rect_label_get_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func DeleteMmod_rect(arg1 Mmod_rect) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_mmod_rect_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))
}

type Mmod_rect interface {
	Swigcptr() uintptr
	SwigIsMmod_rect()
	SetRect(arg2 Rectangle)
	GetRect() (_swig_ret Rectangle)
	SetDetection_confidence(arg2 float64)
	GetDetection_confidence() (_swig_ret float64)
	SetIgnore(arg2 bool)
	GetIgnore() (_swig_ret bool)
	SetLabel(arg2 Std_string)
	GetLabel() (_swig_ret Std_string)
}

func Ignored_mmod_rect(arg1 Rectangle) (_swig_ret Mmod_rect) {
	var swig_r Mmod_rect
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Mmod_rect)(SwigcptrMmod_rect(C._wrap_ignored_mmod_rect_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Serialize__SWIG_3(arg1 Mmod_rect, arg2 Std_ostream) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_serialize__SWIG_3_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Serialize(a ...interface{}) {
	argc := len(a)
	if argc == 2 {
		if _, ok := a[0].(SwigcptrRectangle); !ok {
			goto check_1
		}
		Serialize__SWIG_2(a[0].(Rectangle), a[1].(Std_ostream))
		return
	}
check_1:
	if argc == 2 {
		Serialize__SWIG_3(a[0].(Mmod_rect), a[1].(Std_ostream))
		return
	}
	panic("No match for overloaded function call")
}

func Deserialize__SWIG_3(arg1 Mmod_rect, arg2 Std_istream) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_deserialize__SWIG_3_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Deserialize(a ...interface{}) {
	argc := len(a)
	if argc == 2 {
		if _, ok := a[0].(SwigcptrRectangle); !ok {
			goto check_1
		}
		Deserialize__SWIG_2(a[0].(Rectangle), a[1].(Std_istream))
		return
	}
check_1:
	if argc == 2 {
		Deserialize__SWIG_3(a[0].(Mmod_rect), a[1].(Std_istream))
		return
	}
	panic("No match for overloaded function call")
}

func ProcessRect(arg1 Std_string, arg2 Std_string, arg3 Rectangle) (_swig_ret Full_object_detection) {
	var swig_r Full_object_detection
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	swig_r = (Full_object_detection)(SwigcptrFull_object_detection(C._wrap_ProcessRect_detector_0cbdac121a63e725(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))))
	return swig_r
}


type SwigcptrDlib_vector_Sl_double_Sc_2_Sg_ uintptr
type Dlib_vector_Sl_double_Sc_2_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrDlib_vector_Sl_double_Sc_2_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_vector_Sl_dlib_rectangle_Sg_ uintptr
type Std_vector_Sl_dlib_rectangle_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_dlib_rectangle_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrDlib_vector_Sl_long_Sc_2_Sg_ uintptr
type Dlib_vector_Sl_long_Sc_2_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrDlib_vector_Sl_long_Sc_2_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_string uintptr
type Std_string interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_string) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_ostream uintptr
type Std_ostream interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_ostream) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_istream uintptr
type Std_istream interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_istream) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_vector_Sl_dlib_vector_Sl_long_Sc_2_Sg__Sg_ uintptr
type Std_vector_Sl_dlib_vector_Sl_long_Sc_2_Sg__Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_dlib_vector_Sl_long_Sc_2_Sg__Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

