/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: detector.i

package detector

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef long long swig_type_5;
typedef long long swig_type_6;
typedef long long swig_type_7;
typedef long long swig_type_8;
typedef long long swig_type_9;
typedef long long swig_type_10;
typedef long long swig_type_11;
typedef long long swig_type_12;
typedef long long swig_type_13;
typedef long long swig_type_14;
typedef long long swig_type_15;
typedef long long swig_type_16;
typedef long long swig_type_17;
typedef long long swig_type_18;
typedef long long swig_type_19;
typedef long long swig_type_20;
typedef long long swig_type_21;
typedef long long swig_type_22;
typedef long long swig_type_23;
typedef long long swig_type_24;
typedef long long swig_type_25;
typedef long long swig_type_26;
extern void _wrap_Swig_free_detector_fcc794055f4a9362(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_detector_fcc794055f4a9362(swig_intgo arg1);
extern void _wrap_serialize_detector_fcc794055f4a9362(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_deserialize_detector_fcc794055f4a9362(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_centered_rect__SWIG_0_detector_fcc794055f4a9362(swig_type_1 arg1, swig_type_2 arg2, swig_type_3 arg3, swig_type_4 arg4);
extern uintptr_t _wrap_intersect_detector_fcc794055f4a9362(uintptr_t arg1, uintptr_t arg2);
extern swig_type_5 _wrap_area_detector_fcc794055f4a9362(uintptr_t arg1);
extern uintptr_t _wrap_center_detector_fcc794055f4a9362(uintptr_t arg1);
extern uintptr_t _wrap_dcenter_detector_fcc794055f4a9362(uintptr_t arg1);
extern swig_type_6 _wrap_distance_to_rect_edge_detector_fcc794055f4a9362(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_nearest_point_detector_fcc794055f4a9362(uintptr_t arg1, uintptr_t arg2);
extern swig_type_7 _wrap_nearest_rect_detector_fcc794055f4a9362(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_clip_line_to_rectangle_detector_fcc794055f4a9362(uintptr_t arg1, uintptr_t arg2, uintptr_t arg3);
extern uintptr_t _wrap_centered_rect__SWIG_1_detector_fcc794055f4a9362(uintptr_t arg1, swig_type_8 arg2, swig_type_9 arg3);
extern uintptr_t _wrap_centered_rect__SWIG_2_detector_fcc794055f4a9362(uintptr_t arg1, swig_type_10 arg2, swig_type_11 arg3);
extern uintptr_t _wrap_shrink_rect__SWIG_0_detector_fcc794055f4a9362(uintptr_t arg1, swig_type_12 arg2);
extern uintptr_t _wrap_grow_rect__SWIG_0_detector_fcc794055f4a9362(uintptr_t arg1, swig_type_13 arg2);
extern uintptr_t _wrap_shrink_rect__SWIG_1_detector_fcc794055f4a9362(uintptr_t arg1, swig_type_14 arg2, swig_type_15 arg3);
extern uintptr_t _wrap_grow_rect__SWIG_1_detector_fcc794055f4a9362(uintptr_t arg1, swig_type_16 arg2, swig_type_17 arg3);
extern uintptr_t _wrap_translate_rect__SWIG_0_detector_fcc794055f4a9362(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_translate_rect__SWIG_1_detector_fcc794055f4a9362(uintptr_t arg1, swig_type_18 arg2, swig_type_19 arg3);
extern uintptr_t _wrap_resize_rect_detector_fcc794055f4a9362(uintptr_t arg1, swig_type_20 arg2, swig_type_21 arg3);
extern uintptr_t _wrap_resize_rect_width_detector_fcc794055f4a9362(uintptr_t arg1, swig_type_22 arg2);
extern uintptr_t _wrap_resize_rect_height_detector_fcc794055f4a9362(uintptr_t arg1, swig_type_23 arg2);
extern uintptr_t _wrap_move_rect__SWIG_0_detector_fcc794055f4a9362(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_move_rect__SWIG_1_detector_fcc794055f4a9362(uintptr_t arg1, swig_type_24 arg2, swig_type_25 arg3);
extern uintptr_t _wrap_set_rect_area_detector_fcc794055f4a9362(uintptr_t arg1, swig_type_26 arg2);
extern uintptr_t _wrap_set_aspect_ratio_detector_fcc794055f4a9362(uintptr_t arg1, double arg2);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_detector_fcc794055f4a9362(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Serialize(arg1 Dlib_rectangle, arg2 Std_ostream) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_serialize_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Deserialize(arg1 Dlib_rectangle, arg2 Std_istream) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_deserialize_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func Centered_rect__SWIG_0(arg1 int64, arg2 int64, arg3 uint64, arg4 uint64) (_swig_ret Dlib_rectangle) {
	var swig_r Dlib_rectangle
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (Dlib_rectangle)(SwigcptrDlib_rectangle(C._wrap_centered_rect__SWIG_0_detector_fcc794055f4a9362(C.swig_type_1(_swig_i_0), C.swig_type_2(_swig_i_1), C.swig_type_3(_swig_i_2), C.swig_type_4(_swig_i_3))))
	return swig_r
}

func Intersect(arg1 Dlib_rectangle, arg2 Dlib_rectangle) (_swig_ret Dlib_rectangle) {
	var swig_r Dlib_rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Dlib_rectangle)(SwigcptrDlib_rectangle(C._wrap_intersect_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Area(arg1 Dlib_rectangle) (_swig_ret uint64) {
	var swig_r uint64
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (uint64)(C._wrap_area_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Center(arg1 Dlib_rectangle) (_swig_ret Dlib_vector_Sl_long_Sc_2_Sg_) {
	var swig_r Dlib_vector_Sl_long_Sc_2_Sg_
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Dlib_vector_Sl_long_Sc_2_Sg_)(SwigcptrDlib_vector_Sl_long_Sc_2_Sg_(C._wrap_center_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Dcenter(arg1 Dlib_rectangle) (_swig_ret Dlib_vector_Sl_double_Sc_2_Sg_) {
	var swig_r Dlib_vector_Sl_double_Sc_2_Sg_
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Dlib_vector_Sl_double_Sc_2_Sg_)(SwigcptrDlib_vector_Sl_double_Sc_2_Sg_(C._wrap_dcenter_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Distance_to_rect_edge(arg1 Dlib_rectangle, arg2 Dlib_vector_Sl_long_Sc_2_Sg_) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int64)(C._wrap_distance_to_rect_edge_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Nearest_point(arg1 Dlib_rectangle, arg2 Dlib_vector_Sl_long_Sc_2_Sg_) (_swig_ret Dlib_vector_Sl_long_Sc_2_Sg_) {
	var swig_r Dlib_vector_Sl_long_Sc_2_Sg_
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Dlib_vector_Sl_long_Sc_2_Sg_)(SwigcptrDlib_vector_Sl_long_Sc_2_Sg_(C._wrap_nearest_point_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Nearest_rect(arg1 Std_vector_Sl_dlib_rectangle_Sg_, arg2 Dlib_vector_Sl_long_Sc_2_Sg_) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (int64)(C._wrap_nearest_rect_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Clip_line_to_rectangle(arg1 Dlib_rectangle, arg2 Dlib_vector_Sl_long_Sc_2_Sg_, arg3 Dlib_vector_Sl_long_Sc_2_Sg_) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_clip_line_to_rectangle_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func Centered_rect__SWIG_1(arg1 Dlib_vector_Sl_long_Sc_2_Sg_, arg2 uint64, arg3 uint64) (_swig_ret Dlib_rectangle) {
	var swig_r Dlib_rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Dlib_rectangle)(SwigcptrDlib_rectangle(C._wrap_centered_rect__SWIG_1_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.swig_type_8(_swig_i_1), C.swig_type_9(_swig_i_2))))
	return swig_r
}

func Centered_rect__SWIG_2(arg1 Dlib_rectangle, arg2 uint64, arg3 uint64) (_swig_ret Dlib_rectangle) {
	var swig_r Dlib_rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Dlib_rectangle)(SwigcptrDlib_rectangle(C._wrap_centered_rect__SWIG_2_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.swig_type_10(_swig_i_1), C.swig_type_11(_swig_i_2))))
	return swig_r
}

func Centered_rect(a ...interface{}) Dlib_rectangle {
	argc := len(a)
	if argc == 3 {
		if _, ok := a[0].(SwigcptrDlib_vector_Sl_long_Sc_2_Sg_); !ok {
			goto check_1
		}
		return Centered_rect__SWIG_1(a[0].(Dlib_vector_Sl_long_Sc_2_Sg_), a[1].(uint64), a[2].(uint64))
	}
check_1:
	if argc == 3 {
		return Centered_rect__SWIG_2(a[0].(Dlib_rectangle), a[1].(uint64), a[2].(uint64))
	}
	if argc == 4 {
		return Centered_rect__SWIG_0(a[0].(int64), a[1].(int64), a[2].(uint64), a[3].(uint64))
	}
	panic("No match for overloaded function call")
}

func Shrink_rect__SWIG_0(arg1 Dlib_rectangle, arg2 int64) (_swig_ret Dlib_rectangle) {
	var swig_r Dlib_rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Dlib_rectangle)(SwigcptrDlib_rectangle(C._wrap_shrink_rect__SWIG_0_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.swig_type_12(_swig_i_1))))
	return swig_r
}

func Grow_rect__SWIG_0(arg1 Dlib_rectangle, arg2 int64) (_swig_ret Dlib_rectangle) {
	var swig_r Dlib_rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Dlib_rectangle)(SwigcptrDlib_rectangle(C._wrap_grow_rect__SWIG_0_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.swig_type_13(_swig_i_1))))
	return swig_r
}

func Shrink_rect__SWIG_1(arg1 Dlib_rectangle, arg2 int64, arg3 int64) (_swig_ret Dlib_rectangle) {
	var swig_r Dlib_rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Dlib_rectangle)(SwigcptrDlib_rectangle(C._wrap_shrink_rect__SWIG_1_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.swig_type_14(_swig_i_1), C.swig_type_15(_swig_i_2))))
	return swig_r
}

func Shrink_rect(a ...interface{}) Dlib_rectangle {
	argc := len(a)
	if argc == 2 {
		return Shrink_rect__SWIG_0(a[0].(Dlib_rectangle), a[1].(int64))
	}
	if argc == 3 {
		return Shrink_rect__SWIG_1(a[0].(Dlib_rectangle), a[1].(int64), a[2].(int64))
	}
	panic("No match for overloaded function call")
}

func Grow_rect__SWIG_1(arg1 Dlib_rectangle, arg2 int64, arg3 int64) (_swig_ret Dlib_rectangle) {
	var swig_r Dlib_rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Dlib_rectangle)(SwigcptrDlib_rectangle(C._wrap_grow_rect__SWIG_1_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.swig_type_16(_swig_i_1), C.swig_type_17(_swig_i_2))))
	return swig_r
}

func Grow_rect(a ...interface{}) Dlib_rectangle {
	argc := len(a)
	if argc == 2 {
		return Grow_rect__SWIG_0(a[0].(Dlib_rectangle), a[1].(int64))
	}
	if argc == 3 {
		return Grow_rect__SWIG_1(a[0].(Dlib_rectangle), a[1].(int64), a[2].(int64))
	}
	panic("No match for overloaded function call")
}

func Translate_rect__SWIG_0(arg1 Dlib_rectangle, arg2 Dlib_vector_Sl_long_Sc_2_Sg_) (_swig_ret Dlib_rectangle) {
	var swig_r Dlib_rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Dlib_rectangle)(SwigcptrDlib_rectangle(C._wrap_translate_rect__SWIG_0_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Translate_rect__SWIG_1(arg1 Dlib_rectangle, arg2 int64, arg3 int64) (_swig_ret Dlib_rectangle) {
	var swig_r Dlib_rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Dlib_rectangle)(SwigcptrDlib_rectangle(C._wrap_translate_rect__SWIG_1_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.swig_type_18(_swig_i_1), C.swig_type_19(_swig_i_2))))
	return swig_r
}

func Translate_rect(a ...interface{}) Dlib_rectangle {
	argc := len(a)
	if argc == 2 {
		return Translate_rect__SWIG_0(a[0].(Dlib_rectangle), a[1].(Dlib_vector_Sl_long_Sc_2_Sg_))
	}
	if argc == 3 {
		return Translate_rect__SWIG_1(a[0].(Dlib_rectangle), a[1].(int64), a[2].(int64))
	}
	panic("No match for overloaded function call")
}

func Resize_rect(arg1 Dlib_rectangle, arg2 uint64, arg3 uint64) (_swig_ret Dlib_rectangle) {
	var swig_r Dlib_rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Dlib_rectangle)(SwigcptrDlib_rectangle(C._wrap_resize_rect_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.swig_type_20(_swig_i_1), C.swig_type_21(_swig_i_2))))
	return swig_r
}

func Resize_rect_width(arg1 Dlib_rectangle, arg2 uint64) (_swig_ret Dlib_rectangle) {
	var swig_r Dlib_rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Dlib_rectangle)(SwigcptrDlib_rectangle(C._wrap_resize_rect_width_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.swig_type_22(_swig_i_1))))
	return swig_r
}

func Resize_rect_height(arg1 Dlib_rectangle, arg2 uint64) (_swig_ret Dlib_rectangle) {
	var swig_r Dlib_rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Dlib_rectangle)(SwigcptrDlib_rectangle(C._wrap_resize_rect_height_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.swig_type_23(_swig_i_1))))
	return swig_r
}

func Move_rect__SWIG_0(arg1 Dlib_rectangle, arg2 Dlib_vector_Sl_long_Sc_2_Sg_) (_swig_ret Dlib_rectangle) {
	var swig_r Dlib_rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (Dlib_rectangle)(SwigcptrDlib_rectangle(C._wrap_move_rect__SWIG_0_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))))
	return swig_r
}

func Move_rect__SWIG_1(arg1 Dlib_rectangle, arg2 int64, arg3 int64) (_swig_ret Dlib_rectangle) {
	var swig_r Dlib_rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (Dlib_rectangle)(SwigcptrDlib_rectangle(C._wrap_move_rect__SWIG_1_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.swig_type_24(_swig_i_1), C.swig_type_25(_swig_i_2))))
	return swig_r
}

func Move_rect(a ...interface{}) Dlib_rectangle {
	argc := len(a)
	if argc == 2 {
		return Move_rect__SWIG_0(a[0].(Dlib_rectangle), a[1].(Dlib_vector_Sl_long_Sc_2_Sg_))
	}
	if argc == 3 {
		return Move_rect__SWIG_1(a[0].(Dlib_rectangle), a[1].(int64), a[2].(int64))
	}
	panic("No match for overloaded function call")
}

func Set_rect_area(arg1 Dlib_rectangle, arg2 uint64) (_swig_ret Dlib_rectangle) {
	var swig_r Dlib_rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Dlib_rectangle)(SwigcptrDlib_rectangle(C._wrap_set_rect_area_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.swig_type_26(_swig_i_1))))
	return swig_r
}

func Set_aspect_ratio(arg1 Dlib_rectangle, arg2 float64) (_swig_ret Dlib_rectangle) {
	var swig_r Dlib_rectangle
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (Dlib_rectangle)(SwigcptrDlib_rectangle(C._wrap_set_aspect_ratio_detector_fcc794055f4a9362(C.uintptr_t(_swig_i_0), C.double(_swig_i_1))))
	return swig_r
}


type SwigcptrDlib_vector_Sl_double_Sc_2_Sg_ uintptr
type Dlib_vector_Sl_double_Sc_2_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrDlib_vector_Sl_double_Sc_2_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrDlib_rectangle uintptr
type Dlib_rectangle interface {
	Swigcptr() uintptr;
}
func (p SwigcptrDlib_rectangle) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_vector_Sl_dlib_rectangle_Sg_ uintptr
type Std_vector_Sl_dlib_rectangle_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_vector_Sl_dlib_rectangle_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrDlib_vector_Sl_long_Sc_2_Sg_ uintptr
type Dlib_vector_Sl_long_Sc_2_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrDlib_vector_Sl_long_Sc_2_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_ostream uintptr
type Std_ostream interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_ostream) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrStd_istream uintptr
type Std_istream interface {
	Swigcptr() uintptr;
}
func (p SwigcptrStd_istream) Swigcptr() uintptr {
	return uintptr(p)
}

